<a href="https://colab.research.google.com/github/mehak-aggarwal9300/python/blob/main/python_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Do H.W. 

1.	There are 5280 feet in a mile. Write a Python statement that calculates and prints the number of feet in 13 miles
2.	 Write a Python statement that calculates and prints the number of 	seconds in 7 hours, 21 minutes and 37 seconds.
3.	 The perimeter of a rectangle is 2w+2h, where w and h are the lengths of its sides. Write a Python statement that calculates and prints the length in inches of the perimeter of a rectangle with sides of length 4 	and 7 inches.


In [ ]:
#1
feet_in_mile = 5280 
num_feet = 13 
amount = feet_in_mile * num_feet
amount

68640

In [ ]:
#2
hours=7
min=21
sec=37
sec=hours*60*60 + min*60 +sec
sec

26497

In [ ]:
x=52      

# print("joe is "+str(x)+" years old")  #only str can be concatanated
print("joe is",x,"years old") #without changing to str

joe is 52 years old


In [ ]:
#check

principal = 10000 
rate = .06 
term = 5 
totalinterest = 0 
for year in range(term):
   print(principal) 
   interest = principal * rate 
   print(interest) 
   principal = principal + interest 
   totalinterest = totalinterest + interest 
print(totalinterest) 
print(principal)

10000
600.0
10600.0
636.0
11236.0
674.16
11910.16
714.6096
12624.7696
757.486176
3382.2557759999995
13382.255776


In [ ]:
#Write a password guessing program to keep track of how many times the user has entered the password wrong. 
#If it is more than 3 times, print "You have been denied access." and terminate the program. 
#If the password is correct, print "You have successfully logged in." and terminate the program.




In [ ]:
#Write a program that asks for two numbers. 
#If the sum of the numbers is greater than 100, print "That is a big number" and terminate the program.



In [ ]:
#Write a Python program that accepts a word from the user and reverse it.

In [ ]:
#Write a python program to find those numbers which are divisible by 7 and multiples of 5, between 1500 and 2700.


1. Write a Python program to get the Fibonacci series between 0 to 50. 
2. Write a Python program which iterates the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz“ 
3. Write a Python program to print alphabet pattern 'A'. 
4. Write a Python program to print alphabet pattern 'D‘. 
5. Write a Python program to check whether an alphabet is a vowel or consonant. 
6. Write a Python program to check a triangle is equilateral, isosceles or scalene. 

Note :An equilateral triangle is a triangle in which all three sides are equal.A scalene triangle is a triangle that has three unequal sides.An isosceles triangle is a triangle with (at least) two equal sides.



1.	Wap to output the grade of student based on percentage entered by student

In [ ]:

percent= int(input("Enter percentage:"))
if percent < 60: 
  grade ='F'
elif percent >=60 and percent < 70: 
  grade='D'
elif percent >= 70 and percent < 80:
    grade='C'
elif percent >= 80 and percent < 90: 
      grade='B'
elif percent >= 90 and percent <= 100: 
        grade='A'
        
print(grade)

Enter percentage:67
D


In [ ]:
# print(type({}) is set)
print(type(10))

<class 'int'>


In [ ]:
# aTuple = (1, 'Jhon', 1+3j)
# print(type(aTuple[2:3]))
# print(type([]) is list)
# print(type(0xFF))
# print(bool(0), bool(3.14159), bool(-3), bool(1.0+1j))
type(range(5))


range

In [ ]:
listOne = [20, 40, 60, 80]
listTwo = [20, 40, 60, 80]

print(listOne == listTwo)
print(listOne is listTwo)

True
False


In [ ]:
sampleList = ["Jon", "Kelly", "Jessa"]
sampleList.insert(2,"Scott")  #wrong
print(sampleList)

['Jon', 'Kelly', 'Scott', 'Jessa']


In [ ]:
sampleSet = {"Jodi", "Eric", "Garry"}
sampleSet.add("Vicki")
print(sampleSet)

{'Garry', 'Vicki', 'Jodi', 'Eric'}


In [ ]:
def fun1(num):
    return num + 25

fun1(5)
print(num)

NameError: ignored

In [ ]:
list=["Python","Java","c","C","C++"]
min(list)

'C'

In [ ]:
l=[0,2,5,1]
l2=l[:]

In [ ]:
d={"a":1}
d["a"]=5

In [ ]:
def outerFun(a, b):
    def innerFun(c, d):
        return c + d
    return innerFun(a, b)

res = outerFun(5, 10)
print(res)

15


In [ ]:
def display(**kwargs):
    for i in kwargs:
        print(i)
display(emp="Kelly", salary=9000)

emp
salary


In [ ]:
for i in range(1, 6):
    
    if(i==4):
      continue
    print(i)
else:
    print("this is else block statement" )

1
2
3
5
this is else block statement


In [ ]:
for i in range(10, 15, 1):
  print( i, end=', ')

10, 11, 12, 13, 14, 

In [ ]:
x = 75
def myfunc():
  x = x + 1
  print(x)

myfunc()
print(x)

UnboundLocalError: ignored

2. Wap to check whether the alphabet is a vowel or consonant

In [ ]:
alphabet = input("Enter alphabet:")
alph = alphabet.lower()
if alph in "aeiou":
  print("vowel")
else: print("consonant")

Enter alphabet:i
vowel


In [ ]:
#by using membership operator instead of logical operators 

if alph in "aeiou"

3.	wap to find out the numbers divisible by 5 and 7 between 1500 and 2700 both are included

In [ ]:
# print(2700//5 - 1500//5) by5
# print(2700//7 - 1500//7) by7
# print(2700//35 - 1500//35) by35

for i in range(1500,2701):
    if i%35 == 0:
      print(i)


1505
1540
1575
1610
1645
1680
1715
1750
1785
1820
1855
1890
1925
1960
1995
2030
2065
2100
2135
2170
2205
2240
2275
2310
2345
2380
2415
2450
2485
2520
2555
2590
2625
2660
2695


4.	Take 5 numbers from user and return and print max min and avg of all the numbers

In [ ]:
#way1

import statistics as s
num = int(input("Enter number of elements in list: "))
list1 = []
4

# iterating till num to append elements in list
for i in range(1, num + 1):
    ele = int(input("Enter elements: "))
    list1.append(ele)
      
# print maximum element
print("Largest element is:", max(list1))
print("Smallest element is:", min(list1))
print("Mean is:", s.mean(list1))




Enter number of elements in list: 5
Enter elements: 10
Enter elements: 20
Enter elements: 30
Enter elements: 40
Enter elements: 50
Largest element is: 50
Smallest element is: 10
Mean is: 30


In [ ]:
#way2
def myMax(list1):
  
    # Assume first number in list is largest
    # initially and assign it to variable "max"
    max = list1[0]
    min = list1[0]
    sum=0
    for x in list1:
        sum+=x
        if x > max :
             max = x
        if x < min:
          min = x
    print("Mean is:", sum/5)
    print("Max:", max)
    print("Min: ",min)

  
  
# Driver code
list1 = [10, 20, 4, 45, 99]
myMax(list1)
# print("Largest element is:", myMax(list1))

Mean is: 35.6
Max: 99
Min:  4


In [ ]:
#ma'am 's way to input 5 no.s
#it takes less time to convert string than to take 5 inputs
#when u want to take multiple inputs from user without using for loop

a,b,c,d,e= input("enter 5 numbers").split()
a,b,c,d,e= int(a),int(b),int(c),int(d),int(e)
#convert into list 
list1=[a,b,c,d,e]
list1

enter 5 numbers1 2 3 4 5


[1, 2, 3, 4, 5]

5.	wap to check a triangle is equilateral isosceles or scalene

In [ ]:
A = int(input("Enter side"))
B = int(input("Enter side"))
C = int(input("Enter side"))

if A == B and B == C:
  print("equilateral")
elif A == B or B == C or A == C:
  print("isosceles")
else: 
  print("scalene")

Enter side3
Enter side4
Enter side5
scalene


##30 September

In [ ]:
#1. wap to add  2 matrices


X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
# rt = [[X[i][j] + Y[i][j]  for j in range(len(X[0]))
#           ]
#           for i in range(len(X))
        #  ]
result=[]
for i in range(len(X)):
    res = []  
    for j in range(len(X[0])):
        res.append(X[i][j] + Y[i][j])
    result.append(res)
for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [ ]:
#2. wap to accept a word from user and reverse it

word=input("Enter a word")
w2=word[::-1]
w2

Enter a wordeverything is alright


'thgirla si gnihtyreve'

In [ ]:
#3. Wap to print this pattern
# 1
# 1 2
# 1 2 3
# 1 2 3 4 
# 1 2 3 4 5
def num(n):
  for i in range(1,n+1):
    for j in range(1,i+1):
      print(j,end=" ")
    print("")

num(5)

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
# 4. Wap to print this pattern
# 1
# 2 2
# 3 3 3 
# 4 4 4 4
# 5 5 5 5 5

for i in range(0,6):
  print(str(i)*i)



1
22
333
4444
55555


In [ ]:
#5. Create a list of no.s and find sum,avg,max,min of the numbers


lst = []
n = int(input("Enter number of elements : "))
 
for i in range(0, n):
    ele = int(input())
    lst.append(ele) 

print("max: ",max(lst))
print("min: ",min(lst))
print("sum: ",sum(lst))
print("average0: ",sum(lst)/len(lst))    

Enter number of elements : 5
10
20
3
50
40
max:  50
min:  3
sum:  123
average:  24.6


In [ ]:
#6. Wap to count the occurrences of an element in list


def countX(lst, x):
    count = 0
    for ele in lst:
        if (ele == x):
            count = count + 1
    return count
 
# Driver Code
lst = [8, 6, 8, 10, 8, 20, 10, 8, 8]
x = 8
print(lst.count(x)) #or w/o user defined
print('{} has occurred {} times'.format(x, countX(lst, x)))


5
8 has occurred 5 times


In [ ]:
#WAP that takes a string as input and calculates the frequency of each character using dictionary get function

def count(elements):
	if elements[-1] == '.':
		elements = elements[0:len(elements) - 1]

	if elements in dictionary:
		dictionary[elements] += 1

	else:
		dictionary.update({elements: 1})

Sentence = "Apple Mango Orange Mango Guava Guava Mango"

dictionary = {}

lst = Sentence.split()

for elements in lst:
	count(elements)

for allKeys in dictionary:
	print ("Frequency of ", allKeys, end = " ")
	print (":", end = " ")
	print (dictionary[allKeys], end = " ")
	print()

Frequency of  Apple : 1 
Frequency of  Mango : 3 
Frequency of  Orange : 1 
Frequency of  Guava : 2 


In [ ]:
# better
a=input("enter a string\n")
dict={}
for i in a:
    dict[i]=dict.get(i,0)+1
print(dict)

enter a string
Kanyakumari
{'K': 1, 'a': 3, 'n': 1, 'y': 1, 'k': 1, 'u': 1, 'm': 1, 'r': 1, 'i': 1}


In [ ]:
#Wap to create a list of 20 numbers and divide that list into diff buckets having diff ranges
# Bucket 1 ranges 0-20
# Bucket 2  ranges 21-40
# Bucket 3  ranges 41-60


import random

my_list=[]

for i in range(0,20):
  x=random.randint(0,60)
  my_list.append(x)



#correct this

def divide_chunks(l, n):
	
	# looping till length l
	for i in range(0, len(l), n):
		yield l[i:i + n]

# How many elements each
# list should have
n = int(input("input bucket size"))

x = list(divide_chunks(my_list, n))
print (x)




input bucket size5
[[41, 13, 45, 35, 15], [0, 1, 19, 24, 26], [55, 60, 20, 27, 44], [19, 39, 38, 0, 58]]


In [ ]:
l=[2,3,4,5,6]
l[2:3]


[4]

In [ ]:
#WAP to check validity of password inputted by users
#atleast 1 lower case and 1 upper case 
#1 number between 1 to 9
#minimum length 6 max length 16

#WAP to change given string to new string where 1st and last character have been exchanged

#WAP to input list from user which include duplicate values and you need to return a list of unique values from inputted list

#WAP to pent only strings whose length is greater than equal to 5

#WAP to create a dictionary in which the values are the square of keys

In [ ]:
import re

In [ ]:
#Ques 1- Write a program to check the validity of a password inputted by the user Check
# 1)It includes at least one upper case and Lowe case
# 2) min length 6, max length 16
# 3)must include one number from 0-9

import re

password =input('Enter password')

reg="^(?=.*[a-z])(?=.*[A-Z])(?=.*[0,9])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{6,16}$"
p=reg.compile(reg)
mat=reg.search(p,password)

if mat: 
  print("Valid")
else: 
  print("Invalid")

Enter passwordMehak9


AttributeError: ignored

In [ ]:
#WAP to change given string to new string where 1st and last character have been exchanged


def change_sring(str1):
      return str1[-1:] + str1[1:-1] + str1[:1]
	  
print(change_sring('mehak'))
print(change_sring('12345'))


keham
52341


In [ ]:
def unique_list(l):
  x = []
  for a in l:
    if a not in x:
      x.append(a)
  return x

print(unique_list([1,2,3,3,3,3,4,5])) 


[1, 2, 3, 4, 5]


In [ ]:
# tell all words >k

def string(k,n):
	s = []
	text = n.split(" ")
	for x in text:
		if len(x) > k:
			s.append(x)
	return s
k = 3
n =input("enter string: ")
print(string(k,n))

enter string: na tum jano na hum
['jano']


In [ ]:
# squares of numbers uptil n
n = int(input("enter the Number: "))
d = {}

for x in range(1,n+1):
    d[x] = x**2
    
print("Dictionary = ", d)

enter the Number: 8
Dictionary =  {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


wap to create a form having username password and make sure the password have certain condition: 1 upper case letter, 1 lower case letter and 1 digit

In [ ]:
import tkinter #goto jupyter

In [ ]:
from tkinter import * 
top = tkinter.Tk(className='Tk')
L1 = Label(top, text="User Name") 
L1.pack( side = LEFT) 
E1 = Entry(top, bd =5) 
E1.pack(side = RIGHT) 
X=E1.get() 
top.mainloop()

TclError: ignored

In [ ]:
import numpy as np 
a=np.array([[0,1,2],[2,3,4]])
b=np.array([4,5,6]) 
print(np.add(a,b)) 
print(np.subtract(a,b)) 
print(np.multiply(a,b)) 
print(np.divide(a,b)) 
print(np.dot(a,b))

[[ 4  6  8]
 [ 6  8 10]]
[[-4 -4 -4]
 [-2 -2 -2]]
[[ 0  5 12]
 [ 8 15 24]]
[[0.         0.2        0.33333333]
 [0.5        0.6        0.66666667]]
[17 47]


In [ ]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(a)
print(np.ptp(a)) #7 
print(np.ptp(a,axis=1))#[4,5,7] 
print(np.ptp(a,axis=0))

[[3 7 5]
 [8 4 3]
 [2 4 9]]
7
[4 5 7]
[6 3 6]


In [ ]:
import numpy as np 
a= np.array([[30,65,70],[80,95,10],[50,90,60]]) 
print(np.median(a)) 
print(np.median(a, axis=0)) 
print(np.median(a,axis=1))

65.0
[50. 90. 60.]
[65. 80. 60.]


In [ ]:
import pandas as pd 
import numpy as np 
data = np.array(['a','b','c','d']) 
s = pd.Series(data,index=[100,101,102,103]) 
print( s)

100    a
101    b
102    c
103    d
dtype: object


In [ ]:
import numpy as np 
x = np.linspace(10,20,5) 
print (x)

[10.  12.5 15.  17.5 20. ]


In [ ]:
a ={} 
a.fromkeys(['a', 'b', 'c', 'd'], 98) 
print (a)

{}


In [ ]:
test = {1:'A', 2:'B', 3:'C'} 
del test[1] 
test[1] = 'D' 
del test[2] 
print(len(test))

2


In [ ]:
print("Hello World"[::-1]) 

dlroW olleH


In [ ]:
#  returns a list containing strings,\n
print(type(f.readlines())

SyntaxError: ignored

In [ ]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(np.ptp(a))

7


In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,3) 
print (b)

ValueError: ignored

In [ ]:
import numpy as np 
a=[[1,1],[2,2]] 
print(np.sum(a,axis=0))

[3 3]
